// proto/task.proto
//
// THIS FILE IS THE CONTRACT. Everything else (Go server stubs, Go client
// stubs, the wire format, the field numbering) is generated from this file
// by `protoc`. If you change this file you regenerate the code; you do NOT
// hand-edit the generated Go.

// proto3 = the third major version of the protobuf language.
// In interviews if someone says "are you using proto3 or proto2?" — the
// honest answer is "proto3, like everyone in the last decade." proto2 had
// required/optional keywords; proto3 dropped them by default.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: task.proto

// `package` is the protobuf-level namespace. It prevents name collisions
// when two .proto files define a message with the same name.

package taskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

// TaskID — a wrapper around a single int64.
//
// Why wrap? Because gRPC methods must take a MESSAGE, not a raw int. The
// upside: if you later need to add fields (e.g. include_archived bool), you
// extend the message without breaking the method signature.
type TaskID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // see "field numbers" note below
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskID) Reset() {
	*x = TaskID{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskID) ProtoMessage() {}

func (x *TaskID) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskID.ProtoReflect.Descriptor instead.
func (*TaskID) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TaskStats — what GetTaskStats returns.
type TaskStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks     int32                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks int32                  `protobuf:"varint,2,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	PendingTasks   int32                  `protobuf:"varint,3,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskStats) Reset() {
	*x = TaskStats{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStats) ProtoMessage() {}

func (x *TaskStats) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStats.ProtoReflect.Descriptor instead.
func (*TaskStats) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStats) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *TaskStats) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *TaskStats) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

type TaskCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletion) Reset() {
	*x = TaskCompletion{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletion) ProtoMessage() {}

func (x *TaskCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletion.ProtoReflect.Descriptor instead.
func (*TaskCompletion) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskCompletion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskCompletion) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TaskCompletion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\"\a\n" +
	"\x05Empty\"\x18\n" +
	"\x06TaskID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"z\n" +
	"\tTaskStats\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x02 \x01(\x05R\x0ecompletedTasks\x12#\n" +
	"\rpending_tasks\x18\x03 \x01(\x05R\fpendingTasks\"T\n" +
	"\x0eTaskCompletion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title2}\n" +
	"\x14TaskAnalyticsService\x12,\n" +
	"\fGetTaskStats\x12\v.task.Empty\x1a\x0f.task.TaskStats\x127\n" +
	"\x11GetTaskCompletion\x12\f.task.TaskID\x1a\x14.task.TaskCompletionB5Z3github.com/moonyango/taskbridge/proto/taskpb;taskpbb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_task_proto_goTypes = []any{
	(*Empty)(nil),          // 0: task.Empty
	(*TaskID)(nil),         // 1: task.TaskID
	(*TaskStats)(nil),      // 2: task.TaskStats
	(*TaskCompletion)(nil), // 3: task.TaskCompletion
}
var file_task_proto_depIdxs = []int32{
	0, // 0: task.TaskAnalyticsService.GetTaskStats:input_type -> task.Empty
	1, // 1: task.TaskAnalyticsService.GetTaskCompletion:input_type -> task.TaskID
	2, // 2: task.TaskAnalyticsService.GetTaskStats:output_type -> task.TaskStats
	3, // 3: task.TaskAnalyticsService.GetTaskCompletion:output_type -> task.TaskCompletion
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
