// proto/task.proto
//
// THIS FILE IS THE CONTRACT. Everything else (Go server stubs, Go client
// stubs, the wire format, the field numbering) is generated from this file
// by `protoc`. If you change this file you regenerate the code; you do NOT
// hand-edit the generated Go.

// proto3 = the third major version of the protobuf language.
// In interviews if someone says "are you using proto3 or proto2?" — the
// honest answer is "proto3, like everyone in the last decade." proto2 had
// required/optional keywords; proto3 dropped them by default.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: task.proto

// `package` is the protobuf-level namespace. It prevents name collisions
// when two .proto files define a message with the same name.

package taskpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskAnalyticsService_GetTaskStats_FullMethodName      = "/task.TaskAnalyticsService/GetTaskStats"
	TaskAnalyticsService_GetTaskCompletion_FullMethodName = "/task.TaskAnalyticsService/GetTaskCompletion"
)

// TaskAnalyticsServiceClient is the client API for TaskAnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// SERVICES
// ---------------------------------------------------------------------------
// A `service` defines a set of RPC methods. The code generator turns this
// block into a Go interface on the server side and a Go client struct on
// the client side. You implement the interface; you call methods on the
// client struct. That's it.
//
// Naming convention: <Domain>Service, e.g. TaskAnalyticsService.
type TaskAnalyticsServiceClient interface {
	// One RPC = one method. The pattern is:
	//
	//	rpc <MethodName>(<RequestMessage>) returns (<ResponseMessage>);
	//
	// GetTaskStats takes an Empty (no input) and returns TaskStats.
	// The Empty type is just an empty message — same role as `void` in C.
	GetTaskStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskStats, error)
	// RPC for fetching a single task's completion status. Demonstrates passing
	// a request with one field — the more common case in real APIs.
	GetTaskCompletion(ctx context.Context, in *TaskID, opts ...grpc.CallOption) (*TaskCompletion, error)
}

type taskAnalyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskAnalyticsServiceClient(cc grpc.ClientConnInterface) TaskAnalyticsServiceClient {
	return &taskAnalyticsServiceClient{cc}
}

func (c *taskAnalyticsServiceClient) GetTaskStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStats)
	err := c.cc.Invoke(ctx, TaskAnalyticsService_GetTaskStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAnalyticsServiceClient) GetTaskCompletion(ctx context.Context, in *TaskID, opts ...grpc.CallOption) (*TaskCompletion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskCompletion)
	err := c.cc.Invoke(ctx, TaskAnalyticsService_GetTaskCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskAnalyticsServiceServer is the server API for TaskAnalyticsService service.
// All implementations must embed UnimplementedTaskAnalyticsServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// SERVICES
// ---------------------------------------------------------------------------
// A `service` defines a set of RPC methods. The code generator turns this
// block into a Go interface on the server side and a Go client struct on
// the client side. You implement the interface; you call methods on the
// client struct. That's it.
//
// Naming convention: <Domain>Service, e.g. TaskAnalyticsService.
type TaskAnalyticsServiceServer interface {
	// One RPC = one method. The pattern is:
	//
	//	rpc <MethodName>(<RequestMessage>) returns (<ResponseMessage>);
	//
	// GetTaskStats takes an Empty (no input) and returns TaskStats.
	// The Empty type is just an empty message — same role as `void` in C.
	GetTaskStats(context.Context, *Empty) (*TaskStats, error)
	// RPC for fetching a single task's completion status. Demonstrates passing
	// a request with one field — the more common case in real APIs.
	GetTaskCompletion(context.Context, *TaskID) (*TaskCompletion, error)
	mustEmbedUnimplementedTaskAnalyticsServiceServer()
}

// UnimplementedTaskAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskAnalyticsServiceServer struct{}

func (UnimplementedTaskAnalyticsServiceServer) GetTaskStats(context.Context, *Empty) (*TaskStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStats not implemented")
}
func (UnimplementedTaskAnalyticsServiceServer) GetTaskCompletion(context.Context, *TaskID) (*TaskCompletion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskCompletion not implemented")
}
func (UnimplementedTaskAnalyticsServiceServer) mustEmbedUnimplementedTaskAnalyticsServiceServer() {}
func (UnimplementedTaskAnalyticsServiceServer) testEmbeddedByValue()                              {}

// UnsafeTaskAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskAnalyticsServiceServer will
// result in compilation errors.
type UnsafeTaskAnalyticsServiceServer interface {
	mustEmbedUnimplementedTaskAnalyticsServiceServer()
}

func RegisterTaskAnalyticsServiceServer(s grpc.ServiceRegistrar, srv TaskAnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskAnalyticsService_ServiceDesc, srv)
}

func _TaskAnalyticsService_GetTaskStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAnalyticsServiceServer).GetTaskStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAnalyticsService_GetTaskStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAnalyticsServiceServer).GetTaskStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAnalyticsService_GetTaskCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAnalyticsServiceServer).GetTaskCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAnalyticsService_GetTaskCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAnalyticsServiceServer).GetTaskCompletion(ctx, req.(*TaskID))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskAnalyticsService_ServiceDesc is the grpc.ServiceDesc for TaskAnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskAnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.TaskAnalyticsService",
	HandlerType: (*TaskAnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskStats",
			Handler:    _TaskAnalyticsService_GetTaskStats_Handler,
		},
		{
			MethodName: "GetTaskCompletion",
			Handler:    _TaskAnalyticsService_GetTaskCompletion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
