// Package models holds the shared domain types used across every layer
// of the app (handlers, services, repository, gRPC).
//
// Why a dedicated package? If handlers defined their own Task struct and
// repository defined another one, we'd be forever converting between them.
// One canonical struct = one mental model.
package models

import "time"

// Task is the core domain object. Notice it is a PLAIN struct — no methods,
// no DB tags, no HTTP logic. That keeps it reusable across every layer.
type Task struct {
	// ID is int64 because SQLite's INTEGER PRIMARY KEY maps cleanly to int64.
	// Pick the right integer width on day one; refactoring later is painful.
	ID int64 `json:"id"`

	// Title and Description are exported (capital letter) so encoding/json
	// can SEE them via reflection. If we wrote `title string` (lowercase)
	// the JSON output would be {} and we'd waste 20 minutes debugging.
	Title       string `json:"title"`
	Description string `json:"description"`

	// Completed defaults to false (Go's zero value for bool) — handy because
	// a newly-created task is naturally "not done yet".
	Completed bool `json:"completed"`

	// time.Time serializes to RFC3339 strings in JSON, which is what most
	// frontends and Postman expect. No manual formatting needed.
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// The `json:"..."` strings above are called STRUCT TAGS. They are just
// string literals attached to fields; the encoding/json package reads them
// at runtime using reflection to decide how to name each field in JSON.
//
// Other libraries use the same mechanism with different tag keys, e.g.:
//   `db:"id"`        — used by sqlx
//   `protobuf:"..."` — generated by protoc
// You can stack multiple tags on one field separated by spaces.
